Justin@DESKTOP-64I3O95 MINGW64 ~/desktop/os/pidAllocation (master)
$ py pidAllocation.py

PIDS_IN_USE before calling allocate_pid(): []

Calling allocate_pid() 5 times:

Attempting to allocate a new process to ID 1911...
ID within range...
ID 1911 not in use...
Process established on PID 1911.
----------------------------------
Attempting to allocate a new process to ID 1552...
ID within range...
ID 1552 not in use...
Process established on PID 1552.
----------------------------------
Attempting to allocate a new process to ID 2280...
ID within range...
ID 2280 not in use...
Process established on PID 2280.
----------------------------------
Attempting to allocate a new process to ID 1552...
ID within range...
A PROCESS IS ALREADY RUNNING ON ID 1552... ATTEMPTING 1553.
ID 1553 not in use...
Process established on PID 1553.
----------------------------------
Attempting to allocate a new process to ID 3011...
ID within range...
ID 3011 not in use...
Process established on PID 3011.
----------------------------------

PIDS_IN_USE after calling allocate_pid() 5 times: [1911, 1552, 2280, 1553, 3011]

adding 1234 for testing...

PIDS_IN_USE before calling release_pid(1234): [1911, 1552, 2280, 1553, 3011, 1234]
Attempting to release ID 1234...
ID 1234 released.
PIDS_IN_USE after calling release_pid(1234): [1911, 1552, 2280, 1553, 3011]
